spring.application.name=Backend

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3307/mentoringex
spring.datasource.username=mentoringUser
spring.datasource.password=1234
